name: Unit_Test
on:
  push:
    branches:
      - "main"
    #paths-ignore:
    #  - "README.md"
  pull_request:
    branches:
      - "main"
    #paths-ignore:
    #  - "README.md"

env:
  MAVEN_CUSTOM_OPTS: "-Xmx4g -XX:+ExitOnOutOfMemoryError"

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.5.0
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-2-
      - name: Unit Test
        run: |
          export MAVEN_OPTS="${MAVEN_CUSTOM_OPTS}"
          sudo echo "Asia/Shanghai" > /etc/timezone
          mvn -B install -DskipTests=true -Dautoconfig.skip
          mvn test -B -pl '!polardbx-calcite,!polardbx-rule,!polardbx-rpc' -Dmaven.test.failure.ignore=true
      - name: Analyze Test Result
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Unit Test Result
          report_paths: polardbx-*/target/surefire-reports/TEST-*.xml
          fail_on_test_failures: true
          
